settings:
  APP_DISPLAY_NAME: Element X tcno
  PRODUCTION_APP_NAME: Element X tcno
  APP_GROUP_IDENTIFIER: group.com.dual1208.elementx
  BASE_BUNDLE_IDENTIFIER: com.dual1208.elementx
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: GQZ5664B67
  IS_NIGHTLY_BUILD: false

  # Optional configuration to load accounts from Element Classic.
  CLASSIC_APP_GROUP_IDENTIFIER: group.com.dual1208.element
  CLASSIC_APP_KEYCHAIN_SERVICE_IDENTIFIER: com.dual1208.element.encryption-manager-service
  CLASSIC_APP_KEYCHAIN_ACCESS_GROUP_IDENTIFIER: "$(DEVELOPMENT_TEAM).com.dual1208.element.keychain.shared"
  CLASSIC_APP_DEEP_LINK_URL: "elementxtcno://open"
